# Generated by Django 2.1.2 on 2022-08-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20220804_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
