# Generated by Django 2.1.2 on 2022-08-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_post_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test',
        ),
    ]
