# Generated by Django 3.2.4 on 2022-12-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '중복된 닉네임입니다. 다른 닉네임을 입력하세요.'}, max_length=10),
        ),
    ]
