# Generated by Django 3.2.4 on 2022-11-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
