# Generated by Django 3.2.4 on 2022-12-27 02:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sporty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freepost',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workpost',
            name='date',
        ),
        migrations.AddField(
            model_name='freepost',
            name='end_date_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='끝나는 날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freepost',
            name='start_date_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='시작 날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workpost',
            name='end_date_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='끝나는 날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workpost',
            name='start_date_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='시작 날짜'),
            preserve_default=False,
        ),
    ]
