# Generated by Django 3.2.4 on 2022-11-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='exercise',
            field=models.CharField(choices=[('S', '축구'), ('B', '농구'), ('W', '걷기')], max_length=10),
        ),
    ]
