# Generated by Django 3.2.4 on 2022-11-25 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sporty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketpost',
            name='apply_user_set',
            field=models.ManyToManyField(blank=True, related_name='apply_basketpost_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freepost',
            name='apply_user_set',
            field=models.ManyToManyField(blank=True, related_name='apply_freepost_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workpost',
            name='apply_user_set',
            field=models.ManyToManyField(blank=True, related_name='apply_workpost_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
