# Generated by Django 3.2.4 on 2022-11-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sporty', '0002_alter_post_exercise'),
        ('sporty', '0002_auto_20220916_1833'),
    ]

    operations = [
    ]
