# Generated by Django 3.2.4 on 2023-01-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporty', '0002_auto_20221227_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketpost',
            name='gameinfo',
        ),
        migrations.AddField(
            model_name='basketpost',
            name='hasBall',
            field=models.BooleanField(default=False, verbose_name='공 여부'),
        ),
    ]
