# Generated by Django 3.2.4 on 2022-11-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporty', '0002_auto_20221125_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketpost',
            name='cruit',
            field=models.CharField(default=1, max_length=10, verbose_name='모집인원'),
            preserve_default=False,
        ),
    ]
