# Generated by Django 3.2.4 on 2023-01-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporty', '0002_auto_20221227_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketpost',
            name='gameinfo',
        ),
        migrations.RemoveField(
            model_name='basketpost',
            name='title',
        ),
        migrations.RemoveField(
            model_name='workpost',
            name='purpose',
        ),
        migrations.AddField(
            model_name='basketpost',
            name='amountOfGym',
            field=models.IntegerField(default=0, verbose_name='참가비'),
        ),
        migrations.AddField(
            model_name='basketpost',
            name='questionToApplyer',
            field=models.CharField(default='', max_length=50, verbose_name='신청자한테 궁금한 점'),
        ),
        migrations.AddField(
            model_name='basketpost',
            name='sex',
            field=models.CharField(default='', max_length=5, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='workpost',
            name='isRunning',
            field=models.BooleanField(default=False, verbose_name='목표거리'),
        ),
    ]
