# Generated by Django 3.2.4 on 2023-01-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporty', '0003_auto_20230101_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workpost',
            name='purpose',
        ),
        migrations.AddField(
            model_name='workpost',
            name='isRunning',
            field=models.BooleanField(default=False, verbose_name='목표거리'),
        ),
    ]
