# Generated by Django 3.2.4 on 2023-01-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sporty', '0003_auto_20230108_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workpost',
            name='end_date_time',
        ),
    ]
