# Generated by Django 3.2.4 on 2023-01-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporty', '0004_remove_workpost_end_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freepost',
            name='end_date_time',
        ),
        migrations.RemoveField(
            model_name='freepost',
            name='title',
        ),
        migrations.RemoveField(
            model_name='workpost',
            name='title',
        ),
        migrations.AddField(
            model_name='freepost',
            name='amountOfGym',
            field=models.IntegerField(default=0, verbose_name='참가비'),
        ),
        migrations.AddField(
            model_name='freepost',
            name='sex',
            field=models.CharField(default='', max_length=5, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='workpost',
            name='amountOfGym',
            field=models.IntegerField(default=0, verbose_name='참가비'),
        ),
        migrations.AddField(
            model_name='workpost',
            name='questionToApplyer',
            field=models.CharField(default='', max_length=50, verbose_name='신청자한테 궁금한 점'),
        ),
        migrations.AddField(
            model_name='workpost',
            name='sex',
            field=models.CharField(default='', max_length=5, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='workpost',
            name='isRunning',
            field=models.CharField(default='', max_length=4, verbose_name='달리기 여부'),
        ),
    ]
