# Generated by Django 3.2.4 on 2023-01-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporty', '0005_auto_20230108_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketpost',
            name='end_date_time',
        ),
        migrations.AlterField(
            model_name='basketpost',
            name='cruit',
            field=models.IntegerField(verbose_name='모집인원'),
        ),
    ]
